### ISSUE TITLE
Bring the docs from Codeplex

### ISSUE THREAD

**Issue by alanjds** [fstarred/xrns2xmod#1]
If I understand correctly, they will shutdown on Dec 17 2017 (1 month ago). The docs will be gone in this date!

Please bring the docs to some other place.

**Comment by 01010111** [comment]
I went ahead and migrated them and created a pull request -> https://github.com/fstarred/xrns2xmod/pull/2

**Comment by fstarred** [comment]
@01010111 
Thank you for your contribution.
I moved documentation to [Wiki ](https://github.com/fstarred/xrns2xmod/wiki)page and replaced image refs with _fstarred_, let me know if everything looks ok so I can close this issue
