### ISSUE TITLE
Not working with Renoise 3.2 files

### ISSUE THREAD

**Issue by DoctorWhoof** [fstarred/xrns2xmod#10]
Hi, Xrns2XMod is working fine with the default examples, but when I try to create a very simple new song in Renoise 3.2 I get this:

<img width="480" alt="Screen Shot 2019-09-03 at 3 56 22 PM" src="https://user-images.githubusercontent.com/6250116/64214194-47e8c780-ce64-11e9-897e-a647cf388857.png">

Test file is as basic as can be: created from the XM template, a single pattern, a single sample without envelope, etc.

[test.xrns.zip](https://github.com/fstarred/xrns2xmod/files/3572012/test.xrns.zip)

Thanks!

**Comment by DoctorWhoof** [comment]
Just confirming that it works fine with 3.1. But I'd love to use Renoise 3.2, since it has HiDPI monitor support... thanks!

**Comment by fstarred** [comment]
Released version 5.1.0.0 with the update of the new schema v. 64, compatible with Renoise 3.2.
Please give me a feedback so I can close this issue :)

**Comment by grvaz** [comment]
Archive is corrupted
https://github.com/fstarred/xrns2xmod/releases/download/v5.1.0.0/xrns2xmod_cli_win_x64_5.1.0.0.zip

**Comment by fstarred** [comment]
@grvaz can you retry please ?

**Comment by grvaz** [comment]
now is ok

**Comment by DoctorWhoof** [comment]
Yes, works well with 3.2 now. Thanks!
