### ISSUE TITLE
Update for Renoise 3.3.x doc version 65

### ISSUE THREAD

**Issue by ghost** [fstarred/xrns2xmod#11]
I'm not sure to what extent the .xrns file format may have changed since Renoise 3.2, doc version 64, but the doc version in Renoise 3.3.x is now 65, producing an error on export:
"Song version is not supported by this Xrns2XMod version."
I'm attempting my own update and build in the meantime.
#10

**Comment by fstarred** [comment]
Hello JoeHonk, may you send a merge request with your updates?
Thank you in advance

**Comment by fstarred** [comment]
Released v5.2.0.0 with updated schema. 
Removed schema compliance check
