### ISSUE TITLE
Where is released the Xrns2XModShell.exe

### ISSUE THREAD

**Issue by alanjds** [fstarred/xrns2xmod#3]
Hi.

Installed the tool on Renoise. The ![screen shot 2018-01-21 at 23 02 21](https://user-images.githubusercontent.com/155623/35201072-2d4c551c-feff-11e7-9276-e473fb12096b.png) box searches for `Xrns2XModShell.exe`

I downloaded the Xrns2XMod.zip from the Releases tab on Github, as the Codeplex link does not work. But the needed file is not there. There is only `Xrns2XModUI.exe`.

Where is the searched file?

**Comment by fstarred** [comment]
Forgot to add on the latest [release](https://github.com/fstarred/xrns2xmod/releases/latest).
Please let me know if everything is OK.
Thank you
Starred MediaSoft

**Comment by alanjds** [comment]
Thanks.

I downloaded the new package and it almost works. Display the help on shell, but exits with the error `The type initializer for 'Un4seen.Bass.Bass' threw an exception`.

Well, I am running on Wine 3.0 😬 . Maybe this explains a lot...

The Renoise itself runs fine, and the help output seems ok, but I cannot ensure that the package uploaded is good (nor that it is bad). It just does not work for me.

**Comment by alanjds** [comment]
I tried to compile the solution on MonoDevelop, but there is no MonoDevelop anymore, just Xamarin Studio or Visual Studio for Mac. Then I installed the latest version for my OSX version, but had problems building the solution.

So, I rescued to Wine via PlayOnMac. Renoise installed and ran perfectly. The "tool" installed, but the shell version of xrns2xmod is throwing some 'Un4seen.Bass.Bass' exception.

**Comment by fstarred** [comment]
Try to run _Xrns2XModShell.exe_ under console using the xrns under the resources directory.
Something like:

`Xrns2XModShell.exe -t xm resources\examples\test_adjust_sample_frequency.xrns`

I have just tested it with success.

If you still have an error, try to update these external dependencies:

- Bass.Net [link](https://www.un4seen.com/download.php?bass24)
- bass.dll 
- bassflac.dll [link](https://www.un4seen.com/download.php?bassflac24)
- bassmix.dll [link](https://www.un4seen.com/download.php?bassmix24)

Source: [un4seen](https://www.un4seen.com/bass.html)

System tested:
Windows 10 native

PS
Xrns2XmodCmd has been updated with a bugfix. 

Check this [release](https://github.com/fstarred/xrns2xmod/releases/tag/v2.8.1.0)

**Comment by alanjds** [comment]
Well, I downloaded everything and tried all the DLLs there. On Bass24.Net tried inclusive the v2.0, v4.0 and v4.5. Same error.

Ok. Lets assume that it does not work on Wine 3.0 for now. Will spin a Windows 7 VM and try again... Will post here if worked or not.

Thanks for you help.

**Comment by fstarred** [comment]
Alan, AFAIK mono is still up, take a look on this page:
http://www.mono-project.com/docs/tools+libraries/tools/xbuild/

Btw, the best way to get **xrns2xmod shell** working on non-windows OS would be to use only command line (like xbuild as the link before).

As soon as possible I'll try to set up a linux VM and run xrns2xmod with mono, I'll let you know

**Comment by alanjds** [comment]
Nice. If you need some help, just ask.

After streamlined the right build path, ping me and I'll try to automate the release process via Travis CI. This way you will not need to spin you Linux VM on every release, just when testing build process changes.

**Comment by fstarred** [comment]
Xrns2XMod was updated and succesfully tested under Linux OS with mono.
Reproduced steps:

1. Download [Xrns2XMod latest release](https://github.com/fstarred/xrns2xmod/releases/tag/v2.8.3.0) by choosing the desired installation
1. Install Mono following the steps reported by this [page](http://www.mono-project.com/download/#download-lin)
1. Run`mono Xrns2XModShell.exe`

@alanjds Let me know how things with Travis CI go please, I'm curious 👍

**Comment by alanjds** [comment]
Could you provide a test and a build script? (preferred bash ones 😬)
Then configuring Travis should be a piece of cake

Will test the Linux mono version later.

**Comment by alanjds** [comment]
...maybe I can provide a Docker image or Vagrant recipe later. Is easier than install all the Xamarin stuff on Mac.

**Comment by fstarred** [comment]
If you mean a source build using msbuild, try with this:

`msbuild Xrns2XModCmd/Xrns2XModCmd.csproj /t:build /p:Configuration=Release /p:DebugSymbols=false /p:DebugType=None /p:Platform="x64" /p:OutputPath=<output_path>`

If you succed building, run this on the output directory:

`mono Xrns2XModShell.exe -t xm resources\examples\test_adjust_sample_frequency.xrns`

EDIT:
I didn't upload linux and osx libraries to the source; Do you want to create a complete build from source? Let me know of your intentions so I can help you :)

**Comment by alanjds** [comment]
Yes. This is the plan: have a single script runnable on Linux that generates the binary.

Then tell Travis to run it every push. And store the results for us.

After this working, extend to OSX.

This way people can keep developing on Windows and the CI ensures the Linux/OSX builds w/ no manual effort

**Comment by alanjds** [comment]
I do not know if Travis can do it for Windows builds too. If possible, is desirable. Less manual tasks means less burden of maintenance

**Comment by fstarred** [comment]
It could be helpful if I create a script that run msbuild and generate the complete directory package with the desired libraries? (win, linux or osx according to a parameter given) ?

**Comment by alanjds** [comment]
Very helpful. The final script should install the build dependencies and issue the proper build. But we can go improving with small steps.

Do `msbuild` runs on Linux and/or OSX too? (I got confused after saw https://stackoverflow.com/a/32546122/798575)

I made a fast research, and Travis cannot run on Windows. It will only build OSX & Linux releases for sure. Windows builds maybe w/ some hacks (maybe crosscompiling, maybe wine...)

**Comment by fstarred** [comment]
No, msbuild is a Microsoft tool for building package so is not natively supported on non-Windows OS.
On the same way, mono is not always installed on Linux/OSX, so the user should be aware to install and use it properly.

**Comment by alanjds** [comment]
Hum... I can automate a proper installation of mono on Linux/OSX.

Just to clear: I have only OSX and Linux computers available around me. And a XP virtual machine. Simple tools I can try via Wine.

If is the only way, then generate the Linux & OSX folder and commit is a possible way.

But if we can have only one code and everything is generated automatically from it, so better.

...

Will try to run msbuild via wine and see how hard it breaks... if I manage to download it.

**Comment by alanjds** [comment]
I may have found a way to download `msbuild` for Linux/OSX from official sources!

https://github.com/Microsoft/msbuild/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild

Heading to "dotnet cli". Wish me luck.

**Comment by fstarred** [comment]
Excellent!

Just to clarify:
Both code and binaries are exactly the same for every installations, except that Os X and Linux use three external different libraries (see bass.dll, bassflac.dll, bassmix.dll).

As I underdestand it, it is better to run msbuild on Unix based environment because Travis cannot run on Windows.

Still have some questions through:
Is Travis installed on an external server? How did yoy manage for the required packages described above?

Btw good luck! :)

**Comment by alanjds** [comment]
I see.

Travis is a CI running Ubuntu most of the time, so is easy to `apt-get install` the dotnet packages.

For the DLLs, each build will have to download and pack/release it. All in the CI. This should be easy.

Now is a matter of setting up the build environment on Ubuntu. I am more confident now that it will work, as msbuild is available.

**Comment by alanjds** [comment]
For now:
```bash
$ # Mono
$ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
$ echo "deb http://download.mono-project.com/repo/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/mono-official.list

$ # dotnet (ms)build tool
$ sudo sh -c 'echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
$ sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893

# Install
$ sudo apt-get update
$ sudo apt-get install mono-complete dotnet-sdk-2.0.0-preview3-006701
$ export FrameworkPathOverride=/usr/lib/mono/4.5/

# Build
$ dotnet build -f net45 Xrns2XModCmd/Xrns2XModCmd.csproj /t:build /p:Configuration=Release /p:DebugSymbols=false /p:DebugType=None /p:Platform="x64" /p:OutputPath=/tmp/   
/usr/share/dotnet/sdk/2.0.0-preview3-006729/Microsoft.Common.CurrentVersion.targets(1984,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.XML". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/home/ubuntu/workspace/xrns2xmod/Xrns2XMod/Xrns2XMod.csproj]
/usr/share/dotnet/sdk/2.0.0-preview3-006729/Microsoft.CSharp.CurrentVersion.targets(134,9): warning MSB3884: Could not find rule set file "MinimumRecommendedRules.ruleset". [/home/ubuntu/workspace/xrns2xmod/Xrns2XMod/Xrns2XMod.csproj]
CSC : error CS2001: Source file '/home/ubuntu/workspace/xrns2xmod/Xrns2XMod/ModUtils.cs' could not be found. [/home/ubuntu/workspace/xrns2xmod/Xrns2XMod/Xrns2XMod.csproj]

**Comment by alanjds** [comment]
May you have forgot to commit a file into? Or to unlink the file on the IDE project?

**Comment by fstarred** [comment]
Guess it's a bug of dotnet tool because on Windows all works ok.
Take a look [there,](https://github.com/dotnet/sdk/issues/1406) looks like it's the same issue, also because Xrns2XMod is built on NET 4.5.2.

**Comment by alanjds** [comment]
Thanks for pointing the solution for the warning. But I was talking about the file not found error:

```
CSC : error CS2001: Source file '/home/ubuntu/workspace/xrns2xmod/Xrns2XMod/ModUtils.cs' could not be found. 
```

**Comment by fstarred** [comment]
File exists on repo so I can't see the cause of that error;

[MODUtils.cs](https://github.com/fstarred/xrns2xmod/blob/master/Xrns2XMod/MODUtils.cs)

I guess that issue posted above could cause this unexpected error, but it's just a suspect.

**Comment by alanjds** [comment]
Ah. Is about the case.

On most Unix filesystems `MODUtils.cs` is different file than `ModUtils.cs`.

I checked for the later but not for case mismatches. Thanks and sorry for that.

Will fix and update you.

**Comment by alanjds** [comment]
Had to fix the case issues, then got to build it!
```bash
# dotnet build -f net45 Xrns2XModCmd/Xrns2XModCmd.csproj /t:build /p:Configuration=Release /p:DebugSymbols=false /p:DebugType=None /p:Platform="x64" /p:OutputPath=/tmp/
/usr/share/dotnet/sdk/2.0.0-preview3-006701/Microsoft.CSharp.CurrentVersion.targets(134,9): warning MSB3884: Could not find rule set file "MinimumRecommendedRules.ruleset". [/app/xrns2xmod/Xrns2XMod/Xrns2XMod.csproj]
/usr/share/dotnet/sdk/2.0.0-preview3-006701/Microsoft.Common.CurrentVersion.targets(1984,5): warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190. [/app/xrns2xmod/Xrns2XModCmd/Xrns2XModCmd.csproj]
Microsoft (R) Build Engine version 15.3.402.46929 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/share/dotnet/sdk/2.0.0-preview3-006701/Microsoft.CSharp.CurrentVersion.targets(134,9): warning MSB3884: Could not find rule set file "MinimumRecommendedRules.ruleset". [/app/xrns2xmod/Xrns2XMod/Xrns2XMod.csproj]
  Xrns2XMod -> /tmp/Xrns2XMod.dll
  Consider app.config remapping of assembly "mscorlib, Culture=neutral, PublicKeyToken=b77a5c561934e089" from Version "2.0.0.0" [] to Version "4.0.0.0" [/usr/lib/mono/4.5/mscorlib.dll] to solve conflict and get rid of warning.
  Consider app.config remapping of assembly "System.Xml, Culture=neutral, PublicKeyToken=b77a5c561934e089" from Version "2.0.0.0" [] to Version "4.0.0.0" [/usr/lib/mono/4.5/System.Xml.dll] to solve conflict and get rid of warning.
  Consider app.config remapping of assembly "System, Culture=neutral, PublicKeyToken=b77a5c561934e089" from Version "2.0.0.0" [] to Version "4.0.0.0" [/usr/lib/mono/4.5/System.dll] to solve conflict and get rid of warning.
/usr/share/dotnet/sdk/2.0.0-preview3-006701/Microsoft.Common.CurrentVersion.targets(1984,5): warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190. [/app/xrns2xmod/Xrns2XModCmd/Xrns2XModCmd.csproj]
  Xrns2XModCmd -> /tmp/Xrns2XModShell.exe

Build succeeded.

/usr/share/dotnet/sdk/2.0.0-preview3-006701/Microsoft.CSharp.CurrentVersion.targets(134,9): warning MSB3884: Could not find rule set file "MinimumRecommendedRules.ruleset". [/app/xrns2xmod/Xrns2XMod/Xrns2XMod.csproj]
/usr/share/dotnet/sdk/2.0.0-preview3-006701/Microsoft.Common.CurrentVersion.targets(1984,5): warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190. [/app/xrns2xmod/Xrns2XModCmd/Xrns2XModCmd.csproj]
    2 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.58
```

But still:
```bash
# mono /tmp/Xrns2XModShell.exe -t xm Xrns2XMod/resources/examples/test_adjust_sample_frequency.xrns
The type initializer for 'Un4seen.Bass.Bass' threw an exception.
```

Now I can automate the build and go fiddle w/ the Bass stuff. Should be about trying a bunch of DLLs until some matches :)

**Comment by fstarred** [comment]
Are you sure you have replaced the 3 bass*dll files with the correct ones for your OS ? 
You can find these libraries on the latest release of xrns2xmod, the extension is *.so for Linux and *.dylib for OSx)

**Comment by alanjds** [comment]
No, I had not.

👍 It is what remains. Had no time today to tackle it. 

But it builds!!! 🎉
