### ISSUE TITLE
Error, Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by RyanBram** [fstarred/xrns2xmod#5]
When trying to load this file 
[Battle.zip](https://github.com/fstarred/xrns2xmod/files/1705538/Battle.zip)
 an error message appears.

![renoise error](https://user-images.githubusercontent.com/4508389/35953180-fec40176-0cb5-11e8-9f96-13ae2fa186a0.jpg)

**Comment by fstarred** [comment]
I'll better investigate through this error with renoise, however while debugging looks like no sample data is wrapped from the instruments.

**Comment by RyanBram** [comment]
Oops.
I forgot to inform that the xrns come from MIDI file import. So it should be the problem.

I think I can onvert MIDI to XM  by doing MIDI File  -> Renoise -> XRNX2XMOD -> XM

**Comment by fstarred** [comment]
[Battle.zip](https://github.com/fstarred/xrns2xmod/files/1713402/Battle.zip)

I've added a check when no sample data is present on the instrument, let me know if everything looks ok, so I'll upload a new release with this bugfix.

**Comment by RyanBram** [comment]
Everything looks Ok.
Thanks for the fix.
